import Head from 'next/head'
import { useEffect } from 'react'
import ContactForm from '../components/ContactForm'
import FeaturedProducts from '../components/FeaturedProducts'
import Layout from '../components/Layout'
import Map from '../components/Map'
import ProductsSection from '../components/ProductsSection'
import Slider from '../components/Slider'
import { useStateValue } from '../context/StateProvider'

export default function Home() {
  const [{ }, dispatch] = useStateValue()
  useEffect(() => {
    dispatch({
      type: 'TRIGGER_SIDEBAR',
      isOpenSidebar: false
    })
  }, [])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Slider />
        <ProductsSection />
        <FeaturedProducts />
        <ContactForm />
        <Map />
      </Layout>
    </div>
  )
}
