import Head from 'next/head'
import ContactForm from '../components/ContactForm'
import Footer from '../components/Footer'
import Layout from '../components/Layout'
import ProductsSection from '../components/ProductsSection'
import Slider from '../components/Slider'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Slider />
        <ProductsSection />
        <ContactForm />
        <Footer />
      </Layout>
    </div>
  )
}
